"use client";
import { useEffect, useState } from 'react';
import type { automaticStatus } from '@/lib/quant/automatic';
type Status=Awaited<ReturnType<typeof automaticStatus>>;

// The persisted server schedule and leases decide whether work is actually due.
export function ResearchHeartbeat(){
 useEffect(()=>{let stopped=false;let timer:ReturnType<typeof setTimeout>;
  const tick=async()=>{try{await fetch('/api/quant/automatic',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'tick'})});}catch{/* Status page exposes connection errors. */}finally{if(!stopped)timer=setTimeout(tick,60000);}};
  timer=setTimeout(tick,5000);return()=>{stopped=true;clearTimeout(timer);};
 },[]);return null;
}
export function AutomaticResearchPanel(){
 const [status,setStatus]=useState<Status|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/quant/automatic');const data=await r.json();if(!r.ok)throw new Error(data.error);setStatus(data);}
 useEffect(()=>{let active=true;const refresh=()=>{fetch('/api/quant/automatic').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(active){setStatus(d);setMessage(previous=>previous.startsWith('Connection interrupted:')?'':previous);}}).catch(e=>{if(active)setMessage(`Connection interrupted: ${e.message}. Retrying automatically.`);});};const timer=setTimeout(refresh,0),interval=setInterval(refresh,15000);return()=>{active=false;clearTimeout(timer);clearInterval(interval);};},[]);
 async function action(action:string){setBusy(true);setMessage('');try{const r=await fetch('/api/quant/automatic',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const data=await r.json();if(!r.ok)throw new Error(data.error);setMessage(data.message??(action==='pause'?'Automatic checks paused. An in-progress check may finish.':'Automatic checks enabled.'));await load();}catch(e){setMessage(e instanceof Error?e.message:'Could not update research.');}finally{setBusy(false);}}
 return <section className="quant-guide" aria-label="Automatic research"><h2>Research that follows the market</h2><p>Every hour, check three currency pairs against four fixed strategy ideas. Wait for three finished hourly price periods to agree before treating a change in conditions as settled.</p><p>{status?.enabled?'Automatic checks are enabled.':'Automatic checks are paused or loading.'} Each check uses 90 days of history and estimated opening-and-closing costs of 0.02%.</p><div className="flex flex-wrap gap-3"><button disabled={busy||!status} onClick={()=>void action(status?.enabled?'pause':'enable')}>{status?.enabled?'Pause automatic checks':'Enable automatic checks'}</button><button disabled={busy||!status?.enabled} onClick={()=>void action('tick')}>{busy?'Checking prices…':'Check for new research'}</button></div>{message&&<p role="status">{message}</p>}<div className="quant-grid">{status?.jobs.map(job=><article key={job.instrument}><h3>{job.instrument.replace('_',' / ')}</h3><p>{job.result?.sense.label??'Waiting for the first check'}</p><p>{job.result?.recommendation.explanation??'Connect OANDA. The next available check will test this market.'}</p><p>{job.running?'A check is in progress.':job.completedAt?`Last completed: ${new Date(job.completedAt).toLocaleString()}`:'No completed check yet.'}</p>{job.error&&<p role="status">{job.error}</p>}{job.result&&<details><summary>What was tested</summary><p>{job.result.sense.explanation}</p><p>{job.result.warning}</p>{job.result.reports.map((r:{strategy:{id:string;name:string};performance:{trades:number;netR:number}})=><p key={r.strategy.id}>{r.strategy.name}: {r.performance.trades} reserved-period trades; {r.performance.netR.toFixed(2)} × original risk after estimated costs.</p>)}</details>}</article>)}</div><details><summary>When automatic checks run</summary><p>{status?.driver}</p><p>Each market is checked at most once per hour. Pausing stops new checks. A failed check waits 15 minutes before retrying. Recommendations can change; these checks do not place orders or change a live strategy.</p></details></section>;
}
