CREATE TABLE `system_logs` (
	`id` text PRIMARY KEY NOT NULL,
	`created_at` text NOT NULL,
	`level` text NOT NULL,
	`category` text NOT NULL,
	`event` text NOT NULL,
	`message` text NOT NULL,
	`instrument` text,
	`environment` text,
	`correlation_id` text,
	`duration_ms` integer,
	`details_json` text
);
--> statement-breakpoint
CREATE TABLE `trade_journal` (
	`id` text PRIMARY KEY NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`environment` text NOT NULL,
	`account_id` text,
	`instrument` text NOT NULL,
	`direction` text NOT NULL,
	`style` text NOT NULL,
	`strategy_name` text,
	`setup_type` text,
	`status` text DEFAULT 'planned' NOT NULL,
	`entry_price` real,
	`stop_loss` real,
	`take_profit_1` real,
	`take_profit_2` real,
	`units` integer,
	`lots` real,
	`risk_percent` real,
	`risk_amount` real,
	`pnl` real,
	`broker_trade_id` text,
	`thesis` text,
	`evidence` text,
	`invalidation` text,
	`notes` text,
	`opened_at` text,
	`closed_at` text,
	`metadata_json` text
);
